# defaults file for roles/docker
docker_packages:
- apt-transport-https
- ca-certificates
- curl
- software-properties-common
- docker-ce
- docker-ce-cli
- containerd.io
- python3-docker
- gnupg2
- gnupg
- curl
docker_repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
docker_repo_key: https://download.docker.com/linux/ubuntu/gpg
