- name: Update cache
  shell: sudo apt update


- name: Install Python 3
  apt:
    name:
    - python3
    - python3-pip
    state: present
- name: Ensure dependencies are installed.
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - python3-docker
    - docker-compose
    - git
    state: present




- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install the latest version of Docker Engine on Ubuntu
  package:
    name:
    - docker-ce
    - docker-ce-cli
    # - containerd.io
    state: present

- name: Get the current username
  command: whoami
  register: current_user


- name: Ensure root is added to Docker group if not already a member
  user:
    name: root
    group: docker
    append: true
  become: true

- name: Ensure the current user (aca in this case) is added to Docker group if not already a member
  user:
    name: aca  # Replace with the actual username if needed
    group: docker
    append: true
  become: true


- name: Wait for 10 seconds before starting Docker
  wait_for:
    timeout: 10
- name: Enable and Start Docker
  shell: sudo  systemctl enable docker && systemctl start docker


