- name: Ensure dependencies are installed.
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - python3-docker
    state: present

- name: Update cache
  shell: sudo apt update
  when:
  - ansible_distribution in ["Debian", "Ubuntu"]

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install the latest version of Docker Engine and containerd on Ubuntu
  package:
    name:
    - docker-ce
    - docker-ce-cli
    # - containerd.io
    state: present

